services:
  llm_host:
    build: ollama
    image: jakub-deka/ollama
    container_name: llm_host
    hostname: ollama_debug
    ports:
      - "11700:11434"
    environment:
      - OLLAMA_DEBUG=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  app:
    build: review_app
    image: jakub-deka/review-app
    container_name: review-app
    volumes:
      - ../jupyter_demos://home
    stop_grace_period: 1s